#ifndef _PROJECT_CONFIG_H_
#define _PROJECT_CONFIG_H_

#define USART_DEBUG
#define THERMAL_DATA_UART
#define TMP007_OVERLAY
#define SPLASHSCREEN_OVERLAY
#define ENABLE_LEPTON_AGC

#define USART_DEBUG_SPEED (921600)

#define WHITE_LED_TOGGLE  (HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_6))



#endif


